button.remote.start=/resources/scripts/remote_start.sh
button.remote.stop=/resources/scripts/remote_stop.sh
button.remote.status.novnc=/resources/scripts/remote_status_noVNC.sh
button.remote.status.wayvnc=/resources/scripts/remote_status_wayVNC.sh
button.remote.status.complete=/resources/scripts/remote_status_complete.sh
shell.executable=/bin/bash

#Beispiel für Bestimmung css file (auf installierten Kiste)
#css.file=X:/workspace_web_2025/git/bsc-hc-wayvnc-config/resources/css/pastel.css

#SytemInfoService Pfade 
systeminfoservice.wayvnc.config = /home/bsc/.config/wayvnc/config
systeminfoservice.wayvnc.findpid.ends = /wayvnc
systeminfoservice.novnc.findpid.contains = /usr/share/novnc/utils/novnc_proxy
systeminfoservice.read.username = username=

wayvnc.config=/home/bsc/.config/wayvnc/config